/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.meizu.javacc.mqsql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_BY = 5;
  /** RegularExpression Id. */
  int K_IS = 6;
  /** RegularExpression Id. */
  int K_IN = 7;
  /** RegularExpression Id. */
  int K_OR = 8;
  /** RegularExpression Id. */
  int K_ON = 9;
  /** RegularExpression Id. */
  int K_AND = 10;
  /** RegularExpression Id. */
  int K_NOT = 11;
  /** RegularExpression Id. */
  int K_SET = 12;
  /** RegularExpression Id. */
  int K_ASC = 13;
  /** RegularExpression Id. */
  int K_DESC = 14;
  /** RegularExpression Id. */
  int K_NULL = 15;
  /** RegularExpression Id. */
  int K_LIKE = 16;
  /** RegularExpression Id. */
  int K_FROM = 17;
  /** RegularExpression Id. */
  int K_WHERE = 18;
  /** RegularExpression Id. */
  int K_LIMIT = 19;
  /** RegularExpression Id. */
  int K_ORDER = 20;
  /** RegularExpression Id. */
  int K_SELECT = 21;
  /** RegularExpression Id. */
  int MQ = 22;
  /** RegularExpression Id. */
  int K_AS = 23;
  /** RegularExpression Id. */
  int S_DOUBLE = 24;
  /** RegularExpression Id. */
  int S_INTEGER = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int LINE_COMMENT = 27;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 28;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 31;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 32;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<K_BY>",
    "<K_IS>",
    "<K_IN>",
    "<K_OR>",
    "<K_ON>",
    "<K_AND>",
    "<K_NOT>",
    "<K_SET>",
    "<K_ASC>",
    "<K_DESC>",
    "\"NULL\"",
    "<K_LIKE>",
    "<K_FROM>",
    "<K_WHERE>",
    "<K_LIMIT>",
    "<K_ORDER>",
    "<K_SELECT>",
    "<MQ>",
    "<K_AS>",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"*\"",
  };

}
