options {
STATIC = false;
}

PARSER_BEGIN(Adder)
    package com.meizu.javacc;

    class Adder {
        public static void main(String[] args) throws ParseException, TokenMgrError {
            Adder parser = new Adder(System.in);
            parser.start();
        }
    }
PARSER_END(Adder)

SKIP: {" "}
SKIP: {"\n" | "\r" | "\r\n"}
TOKEN: {<PLUS: "+">}
TOKEN: {<NUMBER: (["0"-"9"])+>}

void start():
{}
{
    <NUMBER>
    (
        <PLUS>
        <NUMBER>
    )*
    <EOF>
}